//! Error-MLP gain parametrization, exported from the wmr-simulator.
//!
//! The simulator tunes a small tanh MLP that maps normalized body-frame
//! tracking errors plus the reference speeds to one bounded multiplicative
//! factor per *scheduled* controller gain:
//!
//! ```text
//! gains[i] = base_gains[i] * clamp(1 + mlp(z)[i], 0, bound)
//! ```
//!
//! Gains not listed in `scheduled_indices` pass through untouched (factor 1).
//! The gain vector layout matches the simulator: [kx, ky, ktheta, kp_inner,
//! ki_inner]. Factors are multiplicative, so they apply to the firmware inner
//! gains even though those use different units than the simulator.
//!
//! The network is loaded from `GAINMLP.JSN` on the SD card, written by
//! `wmr_simulator.pololu.gain_mlp_exporter` (which also documents the JSON
//! schema). Spectral normalization is baked into the exported weights, so the
//! forward pass here is a plain dense tanh network.
//!
//! Host-side golden test: `cargo test --target x86_64-unknown-linux-gnu`
//! checks this implementation against JAX-computed input/output pairs
//! (`tests/data/`, regenerated by `scripts/export_gain_mlp.py --golden`).

#![no_std]

use core::f32::consts::PI;
use heapless::Vec;
use libm::{cosf, fabsf, sinf, tanhf};
use serde::Deserialize;

pub const NUM_FEATURES: usize = 7;
pub const NUM_GAINS: usize = 5;
/// Capacity limits, mirrored in `wmr_simulator/pololu/gain_mlp_exporter.py`.
pub const MAX_HIDDEN_LAYERS: usize = 2;
pub const MAX_WIDTH: usize = 32;
pub const MAX_WEIGHTS: usize = 1600;
const MAX_SIZES: usize = MAX_HIDDEN_LAYERS + 2;

/// Reference setpoint at the current tick (pose, path speed and turn rate).
#[derive(Clone, Copy, Debug, Default)]
pub struct RefSetpoint {
    pub x: f32,
    pub y: f32,
    pub theta: f32,
    pub v: f32,
    pub omega: f32,
}

#[derive(Deserialize)]
struct RawGainMlp<'a> {
    #[serde(default)]
    kind: Option<&'a str>,
    sizes: Vec<usize, MAX_SIZES>,
    scheduled_indices: Vec<usize, NUM_GAINS>,
    bound: f32,
    feature_scale: [f32; NUM_FEATURES],
    weights: Vec<f32, MAX_WEIGHTS>,
}

#[derive(Debug)]
pub struct GainMlp {
    sizes: Vec<usize, MAX_SIZES>,
    scheduled_indices: Vec<usize, NUM_GAINS>,
    bound: f32,
    feature_scale: [f32; NUM_FEATURES],
    weights: Vec<f32, MAX_WEIGHTS>,
}

impl GainMlp {
    pub fn from_json(mut json: &[u8]) -> Result<Self, &'static str> {
        if json.len() >= 3 && &json[..3] == b"\xEF\xBB\xBF" {
            json = &json[3..];
        }
        let (raw, _rem) =
            serde_json_core::from_slice::<RawGainMlp>(json).map_err(|_| "JSON parse failed")?;

        if let Some(kind) = raw.kind {
            if kind != "error_mlp" {
                return Err("unsupported kind");
            }
        }
        if raw.sizes.len() < 2 {
            return Err("sizes too short");
        }
        if raw.sizes[0] != NUM_FEATURES {
            return Err("input size mismatch");
        }
        if *raw.sizes.last().unwrap() != raw.scheduled_indices.len() {
            return Err("output size vs scheduled_indices mismatch");
        }
        if raw.sizes.iter().any(|&s| s == 0 || s > MAX_WIDTH) {
            return Err("layer width out of range");
        }
        for (i, &index) in raw.scheduled_indices.iter().enumerate() {
            if index >= NUM_GAINS {
                return Err("scheduled index out of range");
            }
            if raw.scheduled_indices[..i].contains(&index) {
                return Err("duplicate scheduled index");
            }
        }
        let expected_weights: usize = raw
            .sizes
            .windows(2)
            .map(|pair| pair[1] * pair[0] + pair[1])
            .sum();
        if raw.weights.len() != expected_weights {
            return Err("weights length mismatch");
        }
        if raw.feature_scale.iter().any(|&s| s <= 0.0) {
            return Err("feature_scale must be positive");
        }

        Ok(Self {
            sizes: raw.sizes,
            scheduled_indices: raw.scheduled_indices,
            bound: if raw.bound < 1.0 { 1.0 } else { raw.bound },
            feature_scale: raw.feature_scale,
            weights: raw.weights,
        })
    }

    /// Normalized feature vector; mirrors `error_mlp.features` in the simulator.
    pub fn features(&self, setpoint: &RefSetpoint, pose: &[f32; 3], twist: &[f32; 2]) -> [f32; NUM_FEATURES] {
        let dx = setpoint.x - pose[0];
        let dy = setpoint.y - pose[1];
        let cos_t = cosf(pose[2]);
        let sin_t = sinf(pose[2]);
        let raw = [
            dx * cos_t + dy * sin_t,
            -dx * sin_t + dy * cos_t,
            wrap_pi(setpoint.theta - pose[2]),
            setpoint.v - twist[0],
            setpoint.omega - twist[1],
            setpoint.v,
            fabsf(setpoint.omega),
        ];
        let mut z = [0.0f32; NUM_FEATURES];
        for i in 0..NUM_FEATURES {
            z[i] = raw[i] / self.feature_scale[i];
        }
        z
    }

    /// Multiplicative factor per gain-vector slot; unscheduled slots stay 1.
    pub fn factors(&self, setpoint: &RefSetpoint, pose: &[f32; 3], twist: &[f32; 2]) -> [f32; NUM_GAINS] {
        let z = self.features(setpoint, pose, twist);

        let mut buf_a = [0.0f32; MAX_WIDTH];
        let mut buf_b = [0.0f32; MAX_WIDTH];
        buf_a[..NUM_FEATURES].copy_from_slice(&z);

        let num_layers = self.sizes.len() - 1;
        let mut offset = 0usize;
        for layer in 0..num_layers {
            let fan_in = self.sizes[layer];
            let fan_out = self.sizes[layer + 1];
            let bias_offset = offset + fan_out * fan_in;
            for o in 0..fan_out {
                let row = &self.weights[offset + o * fan_in..offset + (o + 1) * fan_in];
                let mut acc = self.weights[bias_offset + o];
                for i in 0..fan_in {
                    acc += row[i] * buf_a[i];
                }
                buf_b[o] = if layer + 1 < num_layers { tanhf(acc) } else { acc };
            }
            offset = bias_offset + fan_out;
            core::mem::swap(&mut buf_a, &mut buf_b);
        }

        let mut factors = [1.0f32; NUM_GAINS];
        for (o, &index) in self.scheduled_indices.iter().enumerate() {
            factors[index] = (1.0 + buf_a[o]).clamp(0.0, self.bound);
        }
        factors
    }

    /// Full gain vector [kx, ky, ktheta, kp_inner, ki_inner] for one tick.
    pub fn apply(
        &self,
        base_gains: &[f32; NUM_GAINS],
        setpoint: &RefSetpoint,
        pose: &[f32; 3],
        twist: &[f32; 2],
    ) -> [f32; NUM_GAINS] {
        let factors = self.factors(setpoint, pose, twist);
        let mut gains = *base_gains;
        for i in 0..NUM_GAINS {
            gains[i] *= factors[i];
        }
        gains
    }
}

/// Wrap an angle to (-pi, pi]; matches the simulator's `(a + pi) % 2pi - pi`.
fn wrap_pi(angle: f32) -> f32 {
    let two_pi = 2.0 * PI;
    let mut r = (angle + PI) % two_pi;
    if r < 0.0 {
        r += two_pi;
    }
    r - PI
}

#[cfg(test)]
mod tests {
    use super::*;

    // A 7-4-2 network with zero output layer: factors must be exactly 1.
    fn identity_json() -> &'static str {
        concat!(
            r#"{"kind":"error_mlp","sizes":[7,4,2],"scheduled_indices":[0,2],"bound":2.0,"#,
            r#""feature_scale":[0.5,0.5,1.0,2.5,10.0,2.5,10.0],"#,
            r#""weights":[0.1,-0.2,0.3,0.0,0.05,-0.1,0.2,"#, // W0 row 0
            r#"0.0,0.1,0.0,0.2,-0.3,0.1,0.0,"#,
            r#"0.2,0.0,-0.1,0.1,0.0,0.0,0.3,"#,
            r#"-0.1,0.2,0.0,0.0,0.1,-0.2,0.1,"#,
            r#"0.0,0.0,0.0,0.0,"#, // b0
            r#"0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"#, // W1 = 0
            r#"0.0,0.0]}"# // b1 = 0
        )
    }

    #[test]
    fn identity_network_gives_unit_factors() {
        let mlp = GainMlp::from_json(identity_json().as_bytes()).unwrap();
        let setpoint = RefSetpoint { x: 0.3, y: -0.2, theta: 0.5, v: 0.4, omega: 1.0 };
        let factors = mlp.factors(&setpoint, &[0.1, 0.0, 0.2], &[0.3, 0.8]);
        assert_eq!(factors, [1.0; NUM_GAINS]);
        let gains = mlp.apply(&[4.5, 6.0, 12.0, 0.01, 0.02], &setpoint, &[0.1, 0.0, 0.2], &[0.3, 0.8]);
        assert_eq!(gains, [4.5, 6.0, 12.0, 0.01, 0.02]);
    }

    #[test]
    fn wrap_pi_matches_python_mod() {
        assert!((wrap_pi(2.5 * PI) - 0.5 * PI).abs() < 1e-6);
        assert!((wrap_pi(-2.5 * PI) + 0.5 * PI).abs() < 1e-6);
        assert!((wrap_pi(0.1) - 0.1).abs() < 1e-7);
    }

    #[test]
    fn rejects_bad_payloads() {
        assert!(GainMlp::from_json(b"{}").is_err());
        let wrong_len = identity_json().replace("\"bound\":2.0", "\"bound\":2.0,\"sizes\":[7,4,3]");
        let _ = wrong_len; // sizes appears twice -> parse/validation must fail either way
        assert!(GainMlp::from_json(wrong_len.as_bytes()).is_err());
    }
}
